# -*- coding: utf-8 -*-
"""Departure Inspection Report

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZN4K0SwKclKZKt354E4-yr2zY5_ijyG
"""
import streamlit as st
from fpdf import FPDF

import streamlit as st
from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
import requests
from datetime import datetime

# ==========================================
# CONFIGURATION & CONSTANTS
# ==========================================
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "mdshadabk318@gmail.com"
SENDER_PASSWORD = "sqrt ahgl mrgx zidd"
RECEIVER_EMAIL = "housing.lp@qiddiya.fmco.sa"

FMCO_LOGO = "FMCO-Logo-2.png"
QIDDIYA_LOGO = "images (1).png"

# 🔗 PASTE YOUR GOOGLE WEB APP URL DIRECTLY HERE:
GOOGLE_WEBAPP_URL = "https://script.google.com/macros/s/AKfycbzI-LfL3556Jhx53MsbbG2yOgaPn63D0patc19otNoSmDtNU5mVvtOQ43MV3y3p6dy65w/exec"

# ==========================================
# FUNCTION: LOG DATA TO GOOGLE SHEETS VIA WEBAPP
# ==========================================
def log_to_google_sheet(data_dict):
    try:
        # Send data instantly to your Google Sheet webapp connection
        response = requests.post(GOOGLE_WEBAPP_URL, json=data_dict, timeout=10)
        if response.status_code == 200:
            st.success("💾 Data logged permanently to Live Google Sheet database.")
        else:
            st.warning("⚠️ Form submitted locally. Cloud connection busy.")
    except Exception as e:
        st.warning(f"Report secured locally. Cloud sync pending: {e}")

# ==========================================
# PDF GENERATION CLASS
# ==========================================
class DepartureReportPDF(FPDF):
    def __init__(self, room_type, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.room_type = room_type

    def header(self):
        if os.path.exists(FMCO_LOGO):
            self.image(FMCO_LOGO, x=10, y=10, w=35)
        if os.path.exists(QIDDIYA_LOGO):
            self.image(QIDDIYA_LOGO, x=165, y=10, w=35)

        self.ln(18)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(14, 56, 74)
        self.cell(0, 8, "DEPARTURE INSPECTION REPORT", ln=True, align="C")
        self.ln(5)

        self.set_draw_color(14, 56, 74)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | FMCO Operations Logistics Hub", align="C")

    def section_heading(self, label):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(255, 255, 255)
        self.set_fill_color(14, 56, 74)
        self.cell(0, 7, f"  {label}", ln=True, fill=True)
        self.ln(3)

# ==========================================
# SECURE EMAIL ENGINE
# ==========================================
def send_report_via_email(pdf_filename, occupant_name, building, room):
    msg = MIMEMultipart()
    msg['From'] = SENDER_EMAIL
    msg['To'] = RECEIVER_EMAIL
    msg['Subject'] = f"🔔 Departure Report Submitted: Bldg {building} - Room {room} ({occupant_name})"

    body = f"Hello,\n\nA new digital departure room inspection report has been recorded for {occupant_name} (Bldg {building}, Room {room})."
    msg.attach(MIMEText(body, 'plain'))

    try:
        with open(pdf_filename, "rb") as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', f"attachment; filename= {os.path.basename(pdf_filename)}")
            msg.attach(part)

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()
        return True
    except Exception as e:
        st.error(f"Failed to transmit email notification: {e}")
        return False

# ==========================================
# STREAMLIT APPLICATION INTERFACE
# ==========================================
st.set_page_config(page_title="Departure Inspection Form", page_icon="📝", layout="centered")

logo_col1, logo_col2, logo_col3 = st.columns([1, 2, 1])
with logo_col1:
    if os.path.exists(FMCO_LOGO): st.image(FMCO_LOGO, width=120)
with logo_col2:
    st.markdown("<h2 style='text-align: center; color: #0E384A; margin-top: 10px;'>Departure Inspection Report</h2>", unsafe_allow_html=True)
with logo_col3:
    if os.path.exists(QIDDIYA_LOGO): st.image(QIDDIYA_LOGO, width=200)

st.markdown("---")

with st.form("departure_form", clear_on_submit=True):
    st.subheader("🏢 Location & Occupant Core Attributes")
    col1, col2 = st.columns(2)
    with col1:
        occupant_name = st.text_input("Occupant Full Name", placeholder="John Doe")
        building_no = st.text_input("Building Number", placeholder="Bldg 404")
    with col2:
        occupant_id = st.text_input("Resident ID / Serial", placeholder="ID-8849")
        room_no = st.text_input("Room Number", placeholder="Room 201-A")

    room_type = st.radio("**Room Allocation Type**", ["Single Room", "Shared Room"], index=0, horizontal=True)

    st.markdown("---")
    st.subheader("🔍 Facility Infrastructure Checklist")

    # Clean structural key mappings for the script parser
    door_status = st.radio("**Main Door, Locks & Handles**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    wall_status = st.radio("**Wall Condition & Paint Protection**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    floor_status = st.radio("**Primary Flooring & Baseboards**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    window_status = st.radio("**Windowpanes & Latches**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    ac_status = st.radio("**Air Conditioning (AC) Unit & Remote Function**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    light_status = st.radio("**Lighting Fixtures & Electrical Switches**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    bed_status = st.radio("**Bedframe & Mattress Condition**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    wardrobe_status = st.radio("**Wardrobe, Shelving & Cabinet Hinges**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    drainage_status = st.radio("**Bathroom Drainage & Plumbing Assets**", ["Pass (Excellent)", "Action Required"], horizontal=True)
    heater_status = st.radio("**Water Heater Functionality**", ["Pass (Excellent)", "Action Required"], horizontal=True)

    st.markdown("---")
    uploaded_photo = st.file_uploader("Upload Room Condition Photo (Optional)", type=["png", "jpg", "jpeg"])
    remarks = st.text_area("Additional Field Observations")

    col3, col4 = st.columns(2)
    with col3: resident_signature = st.text_input("Resident Signature (Type Name)")
    with col4: inspector_signature = st.text_input("Lead Inspector Signature (Type Name)")

    if st.form_submit_button("Submit Formal Report"):
        if not occupant_name or not building_no or not room_no or not inspector_signature:
            st.error("❌ Error: Fill in all mandatory fields.")
        else:
            record_data = {
                "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "Occupant_Name": occupant_name, "Resident_ID": occupant_id,
                "Building_Number": building_no, "Room_Number": room_no,
                "Room_Type": room_type, "Remarks": remarks,
                "Resident_Signature": resident_signature, "Inspector_Signature": inspector_signature,
                "Door_Status": door_status, "Wall_Status": wall_status, "Floor_Status": floor_status,
                "Window_Status": window_status, "AC_Status": ac_status, "Light_Status": light_status,
                "Bed_Status": bed_status, "Wardrobe_Status": wardrobe_status, "Drainage_Status": drainage_status,
                "Heater_Status": heater_status
            }

            # Instantly sync directly to the Google Sheet online
            log_to_google_sheet(record_data)

            pdf = DepartureReportPDF(room_type=room_type)
            pdf.alias_nb_pages()
            pdf.add_page()
            pdf.section_heading("1. Occupant & Operational Metadata")

            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(40, 7, "Occupant Name:", border=1); pdf.set_font("Helvetica", "", 10); pdf.cell(150, 7, f" {occupant_name}", border=1, ln=True)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(40, 7, "Room Type:", border=1); pdf.set_font("Helvetica", "", 10); pdf.cell(150, 7, f" {room_type}", border=1, ln=True)

            timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
            pdf_filename = f"Departure_Report_{occupant_name.replace(' ', '_')}_{timestamp_str}.pdf"
            pdf.output(pdf_filename)

            if send_report_via_email(pdf_filename, occupant_name, building_no, room_no):
                st.success(f"🎉 Success! PDF compiled and emailed.")
            if os.path.exists(pdf_filename): os.remove(pdf_filename)

