# -*- coding: utf-8 -*-
"""Departure Inspection Report

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZN4K0SwKclKZKt354E4-yr2zY5_ijyG
"""
import streamlit as st
from fpdf import FPDF
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
import requests
from datetime import datetime

# ==========================================
# CONFIGURATION & CONSTANTS
# ==========================================
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "mdshadabk318@gmail.com"
SENDER_PASSWORD = "your-16-character-app-password"  # Replace with your App Password
RECEIVER_EMAIL = "housing.lp@qiddiya.fmco.sa"

FMCO_LOGO = "FMCO-Logo-2.png"
QIDDIYA_LOGO = "images (1).png"

# 🔗 PASTE YOUR GOOGLE WEB APP URL DIRECTLY HERE:
GOOGLE_WEBAPP_URL = "PASTE_YOUR_SCRIPT_URL_HERE"

# ==========================================
# FUNCTION: LOG DATA TO GOOGLE SHEETS
# ==========================================
def log_to_google_sheet(data_dict):
    try:
        response = requests.post(GOOGLE_WEBAPP_URL, json=data_dict, timeout=10)
        if response.status_code == 200:
            st.success("💾 Operational records logged permanently to cloud database.")
        else:
            st.warning("⚠️ Local backup secured. Server response delayed.")
    except Exception as e:
        st.warning(f"Report secured locally. Cloud sync offline: {e}")

# ==========================================
# RESTORED PROFESSIONAL PDF ENGINE
# ==========================================
class DepartureReportPDF(FPDF):
    def __init__(self, room_type, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.room_type = room_type

    def header(self):
        # Balanced top headers
        if os.path.exists(FMCO_LOGO):
            self.image(FMCO_LOGO, x=14, y=12, w=32)
        if os.path.exists(QIDDIYA_LOGO):
            self.image(QIDDIYA_LOGO, x=164, y=11, w=32)
        
        self.ln(16)
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(14, 56, 74) # Corporate Dark Teal
        self.cell(0, 8, "RESIDENT DEPARTURE & INSPECTION REPORT", ln=True, align="C")
        
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.cell(0, 4, f"Generated automatically on: {current_time}", ln=True, align="C")
        self.ln(4)
        
        # Heavy border rule
        self.set_draw_color(14, 56, 74)
        self.set_line_width(0.8)
        self.line(12, self.get_y(), 198, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | FMCO Operations Logistics Hub", align="C")

    def section_heading(self, label):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(255, 255, 255)
        self.set_fill_color(14, 56, 74)
        self.cell(0, 6, f"  {label}", ln=True, fill=True)
        self.ln(2)

# ==========================================
# STREAMLIT INTERFACE WITH MATCHED LOGOS
# ==========================================
st.set_page_config(page_title="Departure Inspection Form", page_icon="📝", layout="centered")

logo_col1, logo_col2, logo_col3 = st.columns([1.2, 2, 1.2])
with logo_col1:
    if os.path.exists(FMCO_LOGO): st.image(FMCO_LOGO, width=140)
with logo_col2:
    st.markdown("<h2 style='text-align: center; color: #0E384A; margin-top: 15px; font-size: 24px; font-weight: bold;'>Departure Inspection Report</h2>", unsafe_allow_html=True)
with logo_col3:
    if os.path.exists(QIDDIYA_LOGO): st.image(QIDDIYA_LOGO, width=240)

st.markdown("---")

with st.form("departure_form", clear_on_submit=True):
    st.subheader("🏢 Location & Occupant Core Attributes")
    col1, col2 = st.columns(2)
    with col1:
        occupant_name = st.text_input("Occupant Full Name", placeholder="e.g. Noor")
        building_no = st.text_input("Building Number", placeholder="e.g. C02")
    with col2:
        occupant_id = st.text_input("Resident ID / Serial", placeholder="e.g. 1234")
        room_no = st.text_input("Room Number", placeholder="e.g. 112")
        
    room_type = st.radio("**Room Allocation Type**", ["Single Room", "Shared Room"], index=0, horizontal=True)
        
    st.markdown("---")
    st.subheader("🔍 Facility Infrastructure Checklist")
    
    # Structural items definition
    items_list = [
        ("Main Door, Locks & Handles", "door"),
        ("Wall Condition & Paint Protection", "wall"),
        ("Primary Flooring & Baseboards", "floor"),
        ("Windowpanes & Latches", "window"),
        ("Air Conditioning (AC) Unit & Remote Function", "ac"),
        ("Lighting Fixtures & Electrical Switches", "light"),
        ("Bedframe & Mattress Condition", "bed"),
        ("Wardrobe, Shelving & Cabinet Hinges", "wardrobe"),
        ("Bathroom Drainage & Plumbing Assets", "drainage"),
        ("Water Heater Functionality", "heater")
    ]
    
    checklist_selections = {}
    for label, key in items_list:
        checklist_selections[label] = st.radio(f"**{label}**", ["Pass (Excellent)", "Action Required (Damage/Defect)"], index=0, horizontal=True)

    st.markdown("---")
    uploaded_photo = st.file_uploader("Upload Room Condition Photo (Optional)", type=["png", "jpg", "jpeg"])
    remarks = st.text_area("Additional Field Observations")
    
    col3, col4 = st.columns(2)
    with col3: resident_signature = st.text_input("Resident Signature (Type Name)")
    with col4: inspector_signature = st.text_input("Lead Inspector Signature (Type Name)")

    if st.form_submit_button("Submit Formal Report"):
        if not occupant_name or not building_no or not room_no or not inspector_signature:
            st.error("❌ Error: Fill in all mandatory field criteria.")
        else:
            # Map values for API delivery
            record_data = {
                "Timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "Occupant_Name": occupant_name, "Resident_ID": occupant_id,
                "Building_Number": building_no, "Room_Number": room_no,
                "Room_Type": room_type, "Remarks": remarks,
                "Resident_Signature": resident_signature, "Inspector_Signature": inspector_signature,
                "Door_Status": checklist_selections["Main Door, Locks & Handles"],
                "Wall_Status": checklist_selections["Wall Condition & Paint Protection"],
                "Floor_Status": checklist_selections["Primary Flooring & Baseboards"],
                "Window_Status": checklist_selections["Windowpanes & Latches"],
                "AC_Status": checklist_selections["Air Conditioning (AC) Unit & Remote Function"],
                "Light_Status": checklist_selections["Lighting Fixtures & Electrical Switches"],
                "Bed_Status": checklist_selections["Bedframe & Mattress Condition"],
                "Wardrobe_Status": checklist_selections["Wardrobe, Shelving & Cabinet Hinges"],
                "Drainage_Status": checklist_selections["Bathroom Drainage & Plumbing Assets"],
                "Heater_Status": checklist_selections["Water Heater Functionality"]
            }
            
            # 1. Post to cloud sheet
            log_to_google_sheet(record_data)
            
            # 2. Re-compile high-fidelity PDF layout
            pdf = DepartureReportPDF(room_type=room_type)
            pdf.alias_nb_pages()
            pdf.add_page()
            
            # SECTION 1: METADATA GRID
            pdf.section_heading("1. Occupant & Operational Metadata")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_fill_color(245, 245, 245)
            
            # Left block
            pdf.cell(35, 7, "Occupant Name:", border=1, fill=True)
            pdf.set_font("Helvetica", "", 10); pdf.cell(60, 7, f" {occupant_name}", border=1)
            # Right block
            pdf.set_font("Helvetica", "B", 10); pdf.cell(35, 7, "Resident ID:", border=1, fill=True)
            pdf.set_font("Helvetica", "", 10); pdf.cell(56, 7, f" {occupant_id}", border=1, ln=True)
            
            # Row 2
            pdf.set_font("Helvetica", "B", 10); pdf.cell(35, 7, "Building No:", border=1, fill=True)
            pdf.set_font("Helvetica", "", 10); pdf.cell(60, 7, f" {building_no}", border=1)
            pdf.set_font("Helvetica", "B", 10); pdf.cell(35, 7, "Room No:", border=1, fill=True)
            pdf.set_font("Helvetica", "", 10); pdf.cell(56, 7, f" {room_no}", border=1, ln=True)
            pdf.ln(5)
            
            # SECTION 2: CHECKLIST
            pdf.section_heading("2. Facility Infrastructure Checklist Evaluations")
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(140, 140, 140)
            pdf.cell(120, 6, "Evaluated Operational Asset Category", border=1, fill=True)
            pdf.cell(66, 6, "Status Verification", border=1, ln=True, fill=True)
            pdf.set_text_color(0, 0, 0)
            
            pdf.set_font("Helvetica", "", 9)
            for asset, status in checklist_selections.items():
                pdf.cell(120, 6, f" {asset}", border=1)
                
                # Dynamic conditional coloring (Green for Pass, Red for Action Required)
                if "Pass" in status:
                    pdf.set_text_color(34, 139, 34)
                    pdf.set_font("Helvetica", "B", 9)
                else:
                    pdf.set_text_color(178, 34, 34)
                    pdf.set_font("Helvetica", "B", 9)
                    
                pdf.cell(66, 6, f" {status}", border=1, ln=True)
                pdf.set_text_color(0, 0, 0)
                pdf.set_font("Helvetica", "", 9)
            pdf.ln(5)
            
            # SECTION 3: FIELD INSPECTION REMARKS
            pdf.section_heading("3. Additional Field Inspection Remarks")
            pdf.set_font("Helvetica", "", 9)
            pdf.multi_cell(0, 6, f" {remarks if remarks else 'No structural deficiencies or critical anomalies noted at evaluation timestamp.'}", border=1)
            pdf.ln(5)
            
            # SECTION 4: SIGNATURE BLOCKS / BRANDING BASE
            pdf.section_heading("4. Signatures & Attestation")
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(93, 5, "Resident Signature Confirmation:", ln=False)
            pdf.cell(93, 5, "Lead Inspector Verification Authorization:", ln=True)
            
            pdf.set_font("Helvetica", "I", 11)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(93, 10, f"   /s/ {resident_signature}", border='B')
            pdf.cell(93, 10, f"   /s/ {inspector_signature}", border='B', ln=True)
            pdf.ln(8)
            
            # Bottom Center Watermark logo branding from previous framework
            if os.path.exists(FMCO_LOGO):
                pdf.image(FMCO_LOGO, x=78, y=pdf.get_y(), w=54)
            
            # Process output and send email
            timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
            pdf_filename = f"Departure_Report_{occupant_name.replace(' ', '_')}_{timestamp_str}.pdf"
            pdf.output(pdf_filename)
            
            if send_report_via_email(pdf_filename, occupant_name, building_no, room_no):
                st.success(f"🎉 Complete structural breakdown report processed and transmitted to inbox.")
            if os.path.exists(pdf_filename): 
                os.remove(pdf_filename)
